version: '3.8'

services:
  mysql:
    image: mysql:8.0.35
    container_name: financial_market_db
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${LOCAL_DB_NAME}
      MYSQL_USER: ${LOCAL_DB_USER}
      MYSQL_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "${LOCAL_DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${LOCAL_DB_ROOT_PASSWORD:-rootpassword}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=200

volumes:
  mysql_data:
