credentials:
  usernames:
    admin:
      name: Admin User
      password: $2b$12$5ZQDfIGsXyCRrXjBYZbZB.ov.7RXUcP9/3y.36h.dDQBsJHjRA3IK
      email: admin@example.com
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - admin@example.com
