"""Initialize Database Tables

Revision ID: 71e76fe6e547
Revises: 
Create Date: 2025-04-07 16:54:19.098032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e76fe6e547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('total_liabilities', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('total_capitalization', sa.Float(), nullable=True),
    sa.Column('common_stock_equity', sa.Float(), nullable=True),
    sa.Column('capital_lease_obligations', sa.Float(), nullable=True),
    sa.Column('net_tangible_assets', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('invested_capital', sa.Float(), nullable=True),
    sa.Column('tangible_book_value', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('shares_issued', sa.Float(), nullable=True),
    sa.Column('ordinary_shares_number', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period_type', name='uix_balance_1')
    )
    op.create_index(op.f('ix_balance_sheet_symbol'), 'balance_sheet', ['symbol'], unique=False)
    op.create_table('cash_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=False),
    sa.Column('investing_cash_flow', sa.Float(), nullable=False),
    sa.Column('financing_cash_flow', sa.Float(), nullable=False),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('end_cash_position', sa.Float(), nullable=True),
    sa.Column('income_tax_paid', sa.Float(), nullable=True),
    sa.Column('interest_paid', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('issuance_of_capital_stock', sa.Float(), nullable=True),
    sa.Column('issuance_of_debt', sa.Float(), nullable=True),
    sa.Column('repayment_of_debt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period_type', name='uix_cash_1')
    )
    op.create_index(op.f('ix_cash_flow_symbol'), 'cash_flow', ['symbol'], unique=False)
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('symbol'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('equity_2_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('risk_type', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('volume_spike', sa.String(length=20), nullable=True),
    sa.Column('RSI', sa.Float(), nullable=True),
    sa.Column('ADR', sa.Float(), nullable=True),
    sa.Column('long_term_persistance', sa.Float(), nullable=True),
    sa.Column('long_term_divergence', sa.Float(), nullable=True),
    sa.Column('earnings_date_score', sa.Float(), nullable=True),
    sa.Column('income_statement_score', sa.Float(), nullable=True),
    sa.Column('cashflow_statement_score', sa.Float(), nullable=True),
    sa.Column('balance_sheet_score', sa.Float(), nullable=True),
    sa.Column('rate_scoring', sa.Float(), nullable=True),
    sa.Column('buy_point', sa.Float(), nullable=True),
    sa.Column('short_point', sa.Float(), nullable=True),
    sa.Column('recommended_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('overbuy_oversold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_2_users_symbol'), 'equity_2_users', ['symbol'], unique=False)
    op.create_table('equity_technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mfi', sa.Float(), nullable=True),
    sa.Column('trend_intensity', sa.Float(), nullable=True),
    sa.Column('persistent_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_technical_indicators_date'), 'equity_technical_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_equity_technical_indicators_symbol'), 'equity_technical_indicators', ['symbol'], unique=False)
    op.create_table('income_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_expense', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('total_operating_income', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.Float(), nullable=True),
    sa.Column('net_non_operating_interest', sa.Float(), nullable=True),
    sa.Column('other_income_expense', sa.Float(), nullable=True),
    sa.Column('pretax_income', sa.Float(), nullable=True),
    sa.Column('tax_provision', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.Column('normalized_income', sa.Float(), nullable=True),
    sa.Column('basic_shares', sa.Float(), nullable=True),
    sa.Column('diluted_shares', sa.Float(), nullable=True),
    sa.Column('basic_eps', sa.Float(), nullable=True),
    sa.Column('diluted_eps', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=False),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('interest_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('net_interest_income', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period_type', name='uix_income_1')
    )
    op.create_index(op.f('ix_income_statement_symbol'), 'income_statement', ['symbol'], unique=False)
    op.create_table('ishare_etf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('subasset_class', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('product_url', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('net_assets', sa.Float(), nullable=True),
    sa.Column('fund_type', sa.String(length=10), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('benchmark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('mmtv_daily_bar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=100), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'field_name', 'field_type')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('related_symbols', sa.String(length=200), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'title', 'published_date', name='uix_news_1')
    )
    op.create_index(op.f('ix_news_articles_published_date'), 'news_articles', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('symbol_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('earnings_release_trading_date_fq', sa.String(length=50), nullable=True),
    sa.Column('earnings_release_next_trading_date_fq', sa.String(length=50), nullable=True),
    sa.Column('indexes', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('yf_daily_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp')
    )
    op.create_table('executives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year_born', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ishare_etf_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ishare_etf_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('asset_class', sa.String(length=100), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notional_value', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.Column('market_currency', sa.String(length=3), nullable=True),
    sa.Column('accrual_date', sa.Date(), nullable=True),
    sa.Column('fund_ticker', sa.String(length=10), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ishare_etf_id'], ['ishare_etf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ishare_etf_holding')
    op.drop_table('executives')
    op.drop_table('yf_daily_bar')
    op.drop_table('symbol_fields')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_date'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('mmtv_daily_bar')
    op.drop_table('ishare_etf')
    op.drop_index(op.f('ix_income_statement_symbol'), table_name='income_statement')
    op.drop_table('income_statement')
    op.drop_index(op.f('ix_equity_technical_indicators_symbol'), table_name='equity_technical_indicators')
    op.drop_index(op.f('ix_equity_technical_indicators_date'), table_name='equity_technical_indicators')
    op.drop_table('equity_technical_indicators')
    op.drop_index(op.f('ix_equity_2_users_symbol'), table_name='equity_2_users')
    op.drop_table('equity_2_users')
    op.drop_table('companies')
    op.drop_index(op.f('ix_cash_flow_symbol'), table_name='cash_flow')
    op.drop_table('cash_flow')
    op.drop_index(op.f('ix_balance_sheet_symbol'), table_name='balance_sheet')
    op.drop_table('balance_sheet')
    # ### end Alembic commands ###
