"""Allow NULL values for financial details tables

Revision ID: ca7a35643e13
Revises: 71e76fe6e547
Create Date: 2025-04-07 17:42:47.661494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca7a35643e13'
down_revision: Union[str, None] = '71e76fe6e547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_sheet', 'total_assets',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('balance_sheet', 'total_liabilities',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('balance_sheet', 'equity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('cash_flow', 'operating_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('cash_flow', 'investing_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('cash_flow', 'financing_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('income_statement', 'revenue',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('income_statement', 'net_income',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('income_statement', 'eps',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income_statement', 'eps',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('income_statement', 'net_income',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('income_statement', 'revenue',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('cash_flow', 'financing_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('cash_flow', 'investing_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('cash_flow', 'operating_cash_flow',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('balance_sheet', 'equity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('balance_sheet', 'total_liabilities',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('balance_sheet', 'total_assets',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
