"""Allow null ticker and icrease length in ETF holdings

Revision ID: cf79e4f4e9c8
Revises: ca7a35643e13
Create Date: 2025-04-08 11:56:43.257082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf79e4f4e9c8'
down_revision: Union[str, None] = 'ca7a35643e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ishare_etf_holding', 'ticker',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ishare_etf_holding', 'ticker',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
