# MySQL connection parameters

[mysql]
host = "${DB_HOST}"
port = "${DB_PORT}"
database = "${DB_NAME}"
user = "${DB_USER}"
password = "${DB_PASSWORD}"

[local_mysql]
host = "${LOCAL_DB_HOST}"
port = "${LOCAL_DB_PORT}"
database = "${LOCAL_DB_NAME}"
user = "${LOCAL_DB_USER}"
password = "${LOCAL_DB_PASSWORD}"

# Admin user for authentication
[credentials]
username = "${STREAMLIT_ADMIN_USERNAME}"
password = "${STREAMLIT_ADMIN_PASSWORD}"